"""Conformance vectors: the golden suite for any other traversal of the same graphs (the browser
visualizer's TypeScript ``sees``). Each vector is (components, proven state, environment) →
expected ``sees()`` per detector and expected ``check`` verdicts, generated by *this* solver from
the canonical jk15 sketch, a BESO-style fan-in branch, a selector-less TMMT and the red-team
edge cases. Divergence is a red CI, never a wrong drawing in the dome.

``optics-conformance [path]`` writes the suite as JSON (default ``optics_conformance.json``).
"""

from __future__ import annotations

import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Iterable, Mapping

from datamodels.optics import ConformanceSuite, ConformanceVector, SelectorState

from obcom.optics.check import check_result
from obcom.optics.compile import default_generator
from obcom.optics.graph import parse_graph
from obcom.optics.kinds import DEFAULT_REGISTRY, KindRegistry
from obcom.optics.sees import sees
from obcom.optics.state import ProvenState

# --- canonical graphs --------------------------------------------------------------------------

#: The v4 jk15 sketch (spec §3; identical to datamodels' ``examples/optics_jk15_example.json``).
JK15: dict = {
    "sky": {"kind": "sky"},
    "flatscreen": {"kind": "flatscreen", "display": {"color": "#e0a030"}},
    "dome": {"kind": "dome", "domeflat_az": 49.0, "optics": {"inputs": {"open": "sky", "flat": "flatscreen"}}},
    "covercalibrator": {"kind": "covercalibrator", "optics": {"from": "dome"}},
    "tertiary": {
        "kind": "tertiaryOCA",
        "device_number": 0,
        "positions": {"beso": {"port": 1, "autoslew-name": "ADR6"}, "andor": {"port": 2, "autoslew-name": "ADR10"}},
        "optics": {"from": "covercalibrator"},
    },
    "derotator": {"kind": "rotator", "optics": {"from": {"tertiary": "andor"}}},
    "pickoff": {"kind": "splitter", "optics": {"from": "derotator"}},
    "filterwheel": {"kind": "filterwheel", "optics": {"from": {"pickoff": "main"}}},
    "guider": {"kind": "camera", "optics": {"from": {"pickoff": "guide"}}},
    "camera": {
        "kind": "camera",
        "optics": {"from": "filterwheel"},
        "paths": {
            "object": "sky.science",
            "snap": "sky.science",
            "focus": "sky.science",
            "skyflat": "sky.flat",
            "domeflat": "flatscreen",
            "zero": "dark",
            "dark": "dark",
            "dark_strict": [
                {"see": "dark", "via": {"covercalibrator": "close"}, "when": "sky.science"},
                {"see": "dark", "via": {"tertiary": "beso"}},
            ],
        },
    },
    "guider_beso": {"kind": "camera", "optics": {"from": {"tertiary": "beso"}}},
}

#: jk15 with a mount, as the real config has it — the dome derivation reads ``domeflat_az_offset``
#: and ``domeflat_alt`` from the ``telescope`` kind; non-optical kinds are simply carried along.
JK15_WITH_MOUNT: dict = {
    **JK15,
    "mount": {"kind": "telescope", "device_number": 0, "domeflat_az_offset": 180.0, "domeflat_alt": 15.0},
    "focuser": {"kind": "focuser", "device_number": 0},
}

#: BESO branch with its real hardware: M4 (sky/calib) fed by the fibre and M5 (thar/white) fed by
#: two lamps — fan-in selectors, no invented lamp wheel. Hangs on jk15's tertiary ``beso`` port.
BESO: dict = {
    "sky": {"kind": "sky"},
    "dome": {"kind": "dome", "optics": {"inputs": {"open": "sky"}}},
    "covercalibrator": {"kind": "covercalibrator", "optics": {"from": "dome"}},
    "tertiary": {
        "kind": "tertiaryOCA",
        "positions": {"beso": {"port": 1}, "andor": {"port": 2}},
        "optics": {"from": "covercalibrator"},
    },
    "fiber": {"kind": "fiber", "optics": {"from": {"tertiary": "beso"}}},
    "thar_lamp": {"kind": "lamp"},
    "white_lamp": {"kind": "lamp"},
    "m5": {"kind": "mirror", "optics": {"inputs": {"thar": "thar_lamp", "white": "white_lamp"}}},
    "m4": {"kind": "mirror", "positions": {"sky": {}, "calib": {}, "park": {}}, "optics": {"inputs": {"sky": "fiber", "calib": "m5"}}},
    "beso": {
        "kind": "spectrograph",
        "optics": {"from": "m4"},
        "paths": {"object": "sky.science", "arc": {"see": "lamp", "via": {"m5": "thar"}}, "flat": {"see": "lamp", "via": {"m5": "white"}}, "dark": "dark"},
    },
    "camera": {"kind": "camera", "optics": {"from": {"tertiary": "andor"}}, "paths": {"object": "sky.science", "dark": "dark"}},
}

#: Three detectors looking at the sky through nothing — feasibility works with no switches at all.
TMMT: dict = {
    "sky": {"kind": "sky"},
    "cam_a": {"kind": "camera", "optics": {"from": "sky"}, "paths": {"object": "sky.science", "skyflat": "sky.flat"}},
    "cam_b": {"kind": "camera", "optics": {"from": "sky"}, "paths": {"object": "sky.science"}},
    "cam_c": {"kind": "camera", "optics": {"from": "sky"}, "paths": {"object": "sky.science"}},
}


# --- scenarios -----------------------------------------------------------------------------------


@dataclass(frozen=True)
class Scenario:
    name: str
    description: str
    components: Mapping
    state: ProvenState
    detectors: tuple[str, ...]
    checks: tuple[tuple[str, str], ...] = field(default_factory=tuple)  #: (detector, function)


_JK15_NIGHT_POSITIONS = {"tertiary": "andor", "covercalibrator": "open", "covercalibrator.calibrator": "off", "dome": "open"}


def _jk15_night(*, moving=(), stale=(), **positions) -> ProvenState:
    """jk15 at astronomical night, imaging configuration, with position overrides."""
    return ProvenState.build({**_JK15_NIGHT_POSITIONS, **positions}, moving=moving, stale=stale, sun_alt_deg=-30.0, dome_shutter_open=True)


def _with_telemetry(state: ProvenState, key: str, telemetry: SelectorState) -> ProvenState:
    return ProvenState(selectors={**state.selectors, key: telemetry}, environment=state.environment, holds=state.holds)


SCENARIOS: tuple[Scenario, ...] = (
    Scenario(
        "jk15 night imaging",
        "M3 on the Andor port, cover open, dome open, astronomical night: the camera sees the science sky; the BESO guider looks at the back of M3.",
        JK15, _jk15_night(), ("camera", "guider", "guider_beso"),
        (("camera", "object"), ("camera", "dark"), ("camera", "dark_strict"), ("camera", "skyflat")),
    ),
    Scenario(
        "jk15 M3 readback unmapped (oca-problems#107)",
        "M3 reports position 2 which maps to no declared symbol: everything downstream is undefined and validates nothing; OBJECT is settable by moving M3.",
        JK15, _with_telemetry(_jk15_night(), "tertiary", SelectorState(position=None, raw=2)),
        ("camera", "guider_beso"), (("camera", "object"), ("camera", "dark")),
    ),
    Scenario(
        "jk15 M3 moving",
        "A moving selector is not proven: undefined until it settles on a mapped position.",
        JK15, _jk15_night(moving=["tertiary"]),
        ("camera",), (("camera", "object"),),
    ),
    Scenario(
        "jk15 stale M3 telemetry",
        "Telemetry older than its truth bound is not proven either (Staleness Contract): undefined.",
        JK15, _jk15_night(stale=["tertiary"]),
        ("camera",), (("camera", "object"),),
    ),
    Scenario(
        "jk15 cover open with calibrator lamp on",
        "The two axes of an Alpaca ICoverCalibrator are independent: the camera sees sky AND lamp — the contaminated-BIAS case a scalar model would have blessed.",
        JK15, _jk15_night(**{"covercalibrator.calibrator": "on"}), ("camera", "guider_beso"),
        (("camera", "object"), ("camera", "zero")),
    ),
    Scenario(
        "jk15 calibrator lamp state unknown",
        "No telemetry for the lamp axis asserts nothing; a lamp axis that is reported but unusable makes the view undefined.",
        JK15, _with_telemetry(_jk15_night(), "covercalibrator.calibrator", SelectorState(position=None, stale=True)),
        ("camera",), (("camera", "object"),),
    ),
    Scenario(
        "jk15 idle branch takes darks",
        "M3 on the BESO port: the imaging camera legitimately sees dark @ tertiary and may take DARKs while the BESO guider sees sky.",
        JK15, _jk15_night(tertiary="beso"), ("camera", "guider", "guider_beso"),
        (("camera", "dark"), ("camera", "dark_strict"), ("camera", "object")),
    ),
    Scenario(
        "jk15 closed cover",
        "Cover closed, lamp off: dark @ covercalibrator for both branches.",
        JK15, _jk15_night(covercalibrator="close"), ("camera", "guider_beso"),
        (("camera", "dark"), ("camera", "dark_strict"), ("camera", "object")),
    ),
    Scenario(
        "jk15 closed cover lit by its calibrator",
        "Cover closed and calibrator on: the closed cover is the flat screen — lamp, not dark.",
        JK15, _jk15_night(covercalibrator="close", **{"covercalibrator.calibrator": "on"}), ("camera",),
        (("camera", "dark"),),
    ),
    Scenario(
        "jk15 daytime",
        "Sun up: OBJECT is impossible (no source provides sky.science), DOMEFLAT is settable by pointing dome and mount at the screen.",
        JK15, _jk15_night().with_environment(sun_alt_deg=20.0), ("camera",),
        (("camera", "object"), ("camera", "domeflat"), ("camera", "dark")),
    ),
    Scenario(
        "jk15 dome derived from environment: at the flat screen",
        "No dome telemetry given as a selector state; shutter open, dome at domeflat_az, mount at domeflat_az+offset and domeflat_alt ⇒ position flat ⇒ flatscreen.",
        JK15_WITH_MOUNT,
        ProvenState.build({"tertiary": "andor", "covercalibrator": "open"}, sun_alt_deg=20.0, dome_shutter_open=True, dome_az_deg=49.0, mount_az_deg=229.0, mount_alt_deg=15.0),
        ("camera",), (("camera", "domeflat"), ("camera", "object")),
    ),
    Scenario(
        "jk15 dome derived from environment: shutter closed",
        "Shutter closed ⇒ the dome is a dark terminal for every detector.",
        JK15_WITH_MOUNT, ProvenState.build({"tertiary": "andor", "covercalibrator": "open"}, sun_alt_deg=-30.0, dome_shutter_open=False),
        ("camera", "guider_beso"), (("camera", "dark"), ("camera", "object")),
    ),
    Scenario(
        "jk15 dome derived from environment: pointing unknown",
        "Shutter open but no azimuths: open or flat cannot be told apart ⇒ undefined @ dome.",
        JK15_WITH_MOUNT, ProvenState.build({"tertiary": "andor", "covercalibrator": "open"}, sun_alt_deg=-30.0, dome_shutter_open=True),
        ("camera",), (("camera", "object"),),
    ),
    Scenario(
        "jk15 twilight skyflat",
        "Sun at -10°: sky.flat is what SKYFLAT needs and OBJECT is impossible.",
        JK15, _jk15_night().with_environment(sun_alt_deg=-10.0), ("camera",),
        (("camera", "skyflat"), ("camera", "object")),
    ),
    Scenario(
        "beso ThAr arc",
        "M4 on calib, M5 on thar: the spectrograph sees the ThAr lamp; the imaging camera on the other M3 port sees dark @ tertiary.",
        BESO, ProvenState.build({"tertiary": "beso", "covercalibrator": "open", "dome": "open", "m4": "calib", "m5": "thar"}, sun_alt_deg=-30.0),
        ("beso", "camera"), (("beso", "arc"), ("beso", "flat"), ("beso", "object"), ("camera", "dark")),
    ),
    Scenario(
        "beso on sky",
        "M4 on sky through the fibre: the spectrograph sees sky.science through tertiary and fibre.",
        BESO, ProvenState.build({"tertiary": "beso", "covercalibrator": "open", "dome": "open", "m4": "sky", "m5": "thar"}, sun_alt_deg=-30.0),
        ("beso",), (("beso", "object"), ("beso", "arc")),
    ),
    Scenario(
        "beso M4 parked",
        "A declared position that is no input transmits nothing: dark @ m4.",
        BESO, ProvenState.build({"tertiary": "beso", "covercalibrator": "open", "dome": "open", "m4": "park", "m5": "thar"}, sun_alt_deg=-30.0),
        ("beso",), (("beso", "dark"), ("beso", "object")),
    ),
    Scenario(
        "beso lamp proven off",
        "A switchable source proven off is a dark terminal itself.",
        BESO, ProvenState.build({"tertiary": "beso", "covercalibrator": "open", "dome": "open", "m4": "calib", "m5": "thar", "thar_lamp": "off"}, sun_alt_deg=-30.0),
        ("beso",), (("beso", "arc"),),
    ),
    Scenario(
        "tmmt three cameras, no selectors",
        "Feasibility without switches: every camera sees the sky; at night OBJECT is active everywhere.",
        TMMT, ProvenState.build({}, sun_alt_deg=-30.0), ("cam_a", "cam_b", "cam_c"),
        (("cam_a", "object"), ("cam_b", "object"), ("cam_a", "skyflat")),
    ),
    Scenario(
        "tmmt sun altitude unknown",
        "A stateful source without its input is undefined — nothing is validated on a guess.",
        TMMT, ProvenState.build({}), ("cam_a",), (("cam_a", "object"),),
    ),
)


def build_vector(scenario: Scenario, registry: KindRegistry = DEFAULT_REGISTRY) -> ConformanceVector:
    graph = parse_graph(scenario.components, registry=registry)
    return ConformanceVector(
        name=scenario.name,
        description=scenario.description,
        components=dict(graph.components),
        state=dict(scenario.state.selectors),
        environment=scenario.state.environment,
        expected_sees={d: sorted(sees(graph, scenario.state, d), key=lambda r: (r.light_class, r.terminal, r.via)) for d in scenario.detectors},
        expected_checks=[check_result(graph, scenario.state, d, f) for d, f in scenario.checks],
    )


def build_suite(scenarios: Iterable[Scenario] = SCENARIOS, registry: KindRegistry = DEFAULT_REGISTRY) -> ConformanceSuite:
    return ConformanceSuite(generated_from=default_generator(), vectors=[build_vector(s, registry) for s in scenarios])


def render(suite: ConformanceSuite) -> str:
    return suite.model_dump_json(by_alias=True, exclude_none=True, indent=2) + "\n"


def main(argv: list[str] | None = None) -> int:
    args = sys.argv[1:] if argv is None else argv
    out = Path(args[0]) if args else Path("optics_conformance.json")
    suite = build_suite()
    out.write_text(render(suite), encoding="utf-8")
    print(f"{len(suite.vectors)} conformance vectors -> {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
